name: test All Tango Code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: awoolley10/tango-test:latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Line length chosen as reasonable project default
        flake8 . --count --docstring-convention google --max-complexity=10 --max-line-length=120 --statistics --ignore=D101,D212
    - name: Test with pytest
      run: |
        pytest -v
