name: test All Tango Code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install python dependencies including flake8 and pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml pytest flake8 flake8-docstrings
    - name: Install R and R package dependencies
      run: |
        sudo apt update
        sudo apt install -y r-base r-base-dev libxml2-dev libssl-dev libcurl4-openssl-dev
    - name: Install required R packages
      run: |
        sudo Rscript -e "install.packages(c('lintr', 'rjson', 'gtools', 'yaml', 'stringi'))"
    - name: Test with pytest
      run: |
        pytest -v
