name: test All Tango Code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:19.10
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools
    - name: Install python dependencies including flake8 and pytest
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pyyaml pytest flake8 flake8-docstrings
    - name: Install R and R package dependencies
      run: |
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y r-base r-base-dev libxml2-dev libssl-dev libcurl4-openssl-dev
    - name: Install required R packages
      run: |
        sudo Rscript -e "install.packages(c('lintr', 'rjson', 'gtools', 'yaml'))"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Line length chosen as reasonable project default
        flake8 . --count --docstring-convention google --max-complexity=10 --max-line-length=120 --statistics --ignore=D101,D212
    - name: Test with pytest
      run: |
        pytest -v
